# Generated by Django 4.1 on 2023-01-27 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lead',
            old_name='emai',
            new_name='email',
        ),
    ]
